import {
    hashPasswd,
    verifyPasswd
} from './hash';

test('hash password and verify it successfully', async() => {
    let result = await hashPasswd('marcus');
    let check = await verifyPasswd('marcus', result);
    expect(check).toBe(true);
});

test('wrong password', async() => {
    let result = await hashPasswd('marcus');
    let check = await verifyPasswd('marcusx', result);
    expect(check).toBe(false);
});

test('hash in the wrong format', () => {
    return verifyPasswd('marcus', 'xxxx').catch(err => {
        expect(err).toEqual(new Error('Invalid hash, must be in MCF, generated by Argon2.'));
    });
});